---

  - name: Installation de apache et php
    yum:
      name: "{{ item }}"
      state: present
    loop:
      "{{ pkg }}"

  - name: Démarrage et activation du service apache2
    systemd:
      name: httpd
      enabled: yes
      state: started

  - name: Arrêt du firewall
    systemd:
        name: firewalld
        enabled: no
        state: stopped

  - name: Suppression des fichiers index.html
    file:
     path: /var/www/html/index.html
     state: absent

  - name : Copie des fichiers php dans /var/www/html/
    copy:
      src: files/index.php
      dest: /var/www/html/

  - name: Ajout du fichier php de la configuraion d'accès à la BDD
    template:
      src: "db-config.php.j2"
      dest: /var/www/html/db-config.php
    notify:
     - restart_apache

## SERVEUR DE BASE DE DONNEES 

  - name: Ajout du dépots epel-release
    yum:
     name: epel-release
     state: present

  - name: Installation de Mariadb et python2-PyMySQL
    yum:
     name:
      - mariadb-server
      - python2-PyMySQL
     state: present

  - name: Démarrage du serveur Mariadb
    systemd:
      name: mariadb
      state: started
      enabled: yes

  - name: Création du fichier client Mariadb
    copy:
      dest: /root/my.cnf
      content: |
        [client]
        user=root
        password=""

  - name: Upload sql table config
    template:
      src: table.sql.j2
      dest: /tmp/table.sql

  - name: Insert table dans mariadb
    mysql_db:
     name: "{{ mysql_dbname }}"
     state: present
     login_user: root
     login_password: ""
     state: import
     target: /tmp/table.sql

  - name: "Create {{ mysql_user }} avec les privileges sur la db {{ mysql_dbname }}"
    mysql_user:
      login_user: root
      login_password: ""
      name: "{{ mysql_user }}"
      password: "{{mysql_password }}"
      priv: "{{ mysql_dbname }}.*:ALL"
      host: "{{ webserver_host }}"
      state: present
